### ISSUE TITLE
Using the Script with GSS108E

### ISSUE THREAD

**Issue by andye2** [mattyribbo/gs108e-bandwidth-prtg#1]
Hi Matty, I found your script after searching a while. Great job, that´s what im looking for. But I´m using a Netgear GSS108E Switch.
In PRTG I got this error: Cookie jar is empty. Dir:C:\WINDOWS\TEMP"
Do you have an adivce for me, whats wrong?

br
Andy

**Comment by mattribbins** [comment]
Hi Andy,

The error is in relation to the cookie file. The script will emulate a login on the web prompt, and will save the authentication cookie into a temp folder for use later.

In C:\Windows\Temp there should be a file called .gs108ecookie - Can you confirm if this file is in your temp folder?

Can you let me know what firmware version you are using as well please. The GSS108E in theory uses the same firmware as the GS108E.

**Comment by andye2** [comment]
Hi and thanks for your fast Feedback. 
I just looked into the Temp Folder but there is no cookie files with such a name. 
The current firmware i´m using is the V1.0.0.10.

Find attached some screenshots, maybe it can be helpful.

![image](https://user-images.githubusercontent.com/41288434/42772360-798a62f6-892a-11e8-9a4f-99aaa8394ecc.png)

![image](https://user-images.githubusercontent.com/41288434/42772267-397d676c-892a-11e8-854d-4909ed9e6d69.png)

![image](https://user-images.githubusercontent.com/41288434/42772297-4c79aff6-892a-11e8-8a52-bb1ea75dd009.png)

It nearly looks the same as the GS108E do.

This my PRTG Setting.
![image](https://user-images.githubusercontent.com/41288434/42772616-43ccad8a-892b-11e8-96cc-7411f4f5c5a6.png)

Thanks in advance
br Andy

**Comment by mattribbins** [comment]
Hi, your settings look correct, and the UI appears exactly the same to the GS108EV3 I own. What I suspect is happening is the PRTG script can't write the cookie temporary file.
What OS are you running PRTG on?

**Comment by andye2** [comment]
Hi, my OS ist Win10 Pro. 
In the past I had trouble with a poweshell script and PRTG. I had to give Admin rights in the poweshell window. 
Perhaps it is the same issue with phyton.  Do you know?

br andy

**Comment by mattribbins** [comment]
I am suspecting there is a permissions issue somewhere. The Python script can't write to the temporary folder for some reason, hence your error and the script not working correctly. I will need to test on Windows 10. I've only tested on Windows Server 2012 R2, which shouldn't differ too much.

**Comment by mattribbins** [comment]
I believe I have found the issue relating to old firmware and the way it handles the port statistics. Sorry it took a while to figure out, only recently acquired an older device with old firmware.
